//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_Profile
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "User Id")]
            [Required(ErrorMessage = "User Id is Required.")]	
            public virtual System.Guid UserId { get; set; }	
            
            [Display(Name = "Property Names")]
            [Required(ErrorMessage = "Property Names is Required.")]	
            public virtual string PropertyNames { get; set; }	
            
            [Display(Name = "Property Values String")]
            [Required(ErrorMessage = "Property Values String is Required.")]	
            public virtual string PropertyValuesString { get; set; }	
            
            [Display(Name = "Property Values Binary")]
            [Required(ErrorMessage = "Property Values Binary is Required.")]	
            public virtual byte[] PropertyValuesBinary { get; set; }	
            
            [Display(Name = "Last Updated Date")]
            [Required(ErrorMessage = "Last Updated Date is Required.")]	
            public virtual System.DateTime LastUpdatedDate { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual aspnet_Users aspnet_Users { get; set; }

            #endregion
    	}

        #endregion
    }
}
