//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_Roles
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Application Id")]
            [Required(ErrorMessage = "Application Id is Required.")]	
            public virtual System.Guid ApplicationId { get; set; }	
            
            [Display(Name = "Role Id")]
            [Required(ErrorMessage = "Role Id is Required.")]	
            public virtual System.Guid RoleId { get; set; }	
            
            [Display(Name = "Role Name")]
            [Required(ErrorMessage = "Role Name is Required.")]
            [StringLength(256, ErrorMessage = "Role Name must be under 256 characters.")]	
            public virtual string RoleName { get; set; }	
            
            [Display(Name = "Lowered Role Name")]
            [Required(ErrorMessage = "Lowered Role Name is Required.")]
            [StringLength(256, ErrorMessage = "Lowered Role Name must be under 256 characters.")]	
            public virtual string LoweredRoleName { get; set; }	
            
            [Display(Name = "Description")]
            [StringLength(256, ErrorMessage = "Description must be under 256 characters.")]	
            public virtual string Description { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual aspnet_Applications aspnet_Applications { get; set; }
            	
            public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }

            #endregion
    	}

        #endregion
    }
}
