//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_Paths
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Application Id")]
            [Required(ErrorMessage = "Application Id is Required.")]	
            public virtual System.Guid ApplicationId { get; set; }	
            
            [Display(Name = "Path Id")]
            [Required(ErrorMessage = "Path Id is Required.")]	
            public virtual System.Guid PathId { get; set; }	
            
            [Display(Name = "Path")]
            [Required(ErrorMessage = "Path is Required.")]
            [StringLength(256, ErrorMessage = "Path must be under 256 characters.")]	
            public virtual string Path { get; set; }	
            
            [Display(Name = "Lowered Path")]
            [Required(ErrorMessage = "Lowered Path is Required.")]
            [StringLength(256, ErrorMessage = "Lowered Path must be under 256 characters.")]	
            public virtual string LoweredPath { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual aspnet_Applications aspnet_Applications { get; set; }
            	
            public virtual aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers { get; set; }
            	
            public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }

            #endregion
    	}

        #endregion
    }
}
