//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_Users
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Application Id")]
            [Required(ErrorMessage = "Application Id is Required.")]	
            public virtual System.Guid ApplicationId { get; set; }	
            
            [Display(Name = "User Id")]
            [Required(ErrorMessage = "User Id is Required.")]	
            public virtual System.Guid UserId { get; set; }	
            
            [Display(Name = "User Name")]
            [Required(ErrorMessage = "User Name is Required.")]
            [StringLength(256, ErrorMessage = "User Name must be under 256 characters.")]	
            public virtual string UserName { get; set; }	
            
            [Display(Name = "Lowered User Name")]
            [Required(ErrorMessage = "Lowered User Name is Required.")]
            [StringLength(256, ErrorMessage = "Lowered User Name must be under 256 characters.")]	
            public virtual string LoweredUserName { get; set; }	
            
            [Display(Name = "Mobile Alias")]
            [StringLength(16, ErrorMessage = "Mobile Alias must be under 16 characters.")]	
            public virtual string MobileAlias { get; set; }	
            
            [Display(Name = "Is Anonymous")]
            [Required(ErrorMessage = "Is Anonymous is Required.")]	
            public virtual bool IsAnonymous { get; set; }	
            
            [Display(Name = "Last Activity Date")]
            [Required(ErrorMessage = "Last Activity Date is Required.")]	
            public virtual System.DateTime LastActivityDate { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual aspnet_Applications aspnet_Applications { get; set; }
            	
            public virtual aspnet_Membership aspnet_Membership { get; set; }
            	
            public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
            	
            public virtual aspnet_Profile aspnet_Profile { get; set; }
            	
            public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }

            #endregion
    	}

        #endregion
    }
}
