//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_Applications
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Application Name")]
            [Required(ErrorMessage = "Application Name is Required.")]
            [StringLength(256, ErrorMessage = "Application Name must be under 256 characters.")]	
            public virtual string ApplicationName { get; set; }	
            
            [Display(Name = "Lowered Application Name")]
            [Required(ErrorMessage = "Lowered Application Name is Required.")]
            [StringLength(256, ErrorMessage = "Lowered Application Name must be under 256 characters.")]	
            public virtual string LoweredApplicationName { get; set; }	
            
            [Display(Name = "Application Id")]
            [Required(ErrorMessage = "Application Id is Required.")]	
            public virtual System.Guid ApplicationId { get; set; }	
            
            [Display(Name = "Description")]
            [StringLength(256, ErrorMessage = "Description must be under 256 characters.")]	
            public virtual string Description { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual ICollection<aspnet_Membership> aspnet_Membership { get; set; }
            	
            public virtual ICollection<aspnet_Paths> aspnet_Paths { get; set; }
            	
            public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
            	
            public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }

            #endregion
    	}

        #endregion
    }
}
