//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class aspnet_PersonalizationAllUsers
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Path Id")]
            [Required(ErrorMessage = "Path Id is Required.")]	
            public virtual System.Guid PathId { get; set; }	
            
            [Display(Name = "Page Settings")]
            [Required(ErrorMessage = "Page Settings is Required.")]	
            public virtual byte[] PageSettings { get; set; }	
            
            [Display(Name = "Last Updated Date")]
            [Required(ErrorMessage = "Last Updated Date is Required.")]	
            public virtual System.DateTime LastUpdatedDate { get; set; }	

            #endregion
    
    
            #region Navigation Properties
            	
            public virtual aspnet_Paths aspnet_Paths { get; set; }

            #endregion
    	}

        #endregion
    }
}
