//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Blueapps.Core.Domain
{
    [Serializable()]
    public partial class Device
    {
        #region Primitive Properties
    
        public virtual int DeviceID
        {
            get;
            set;
        }
    
        public virtual string DeviceName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CreatedByUserID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DisplayOrder
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsVisible
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateCreated
        {
            get;
            set;
        }

        #endregion
    }
}
