//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Blueapps.Core.Domain
{
    [MetadataType(typeof(Metadata))]
    public partial class Device
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "DeviceID")]
            [Required(ErrorMessage = "DeviceID is Required.")]	
            public virtual int DeviceID { get; set; }	
            
            [Display(Name = "Device Name")]
            [StringLength(50, ErrorMessage = "Device Name must be under 50 characters.")]	
            public virtual string DeviceName { get; set; }	
            
            [Display(Name = "Description")]
            [StringLength(1000, ErrorMessage = "Description must be under 1000 characters.")]	
            public virtual string Description { get; set; }	
            
            [Display(Name = "CreatedByUserID")]	
            public virtual Nullable<int> CreatedByUserID { get; set; }	
            
            [Display(Name = "Display Order")]	
            public virtual Nullable<int> DisplayOrder { get; set; }	
            
            [Display(Name = "Is Visible")]	
            public virtual Nullable<bool> IsVisible { get; set; }	
            
            [Display(Name = "Date Created")]	
            public virtual Nullable<System.DateTime> DateCreated { get; set; }	

            #endregion
    
    
    	}

        #endregion
    }
}
